// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrdersItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteProduct(ctx context.Context, id int64) error
	GetAllOrders(ctx context.Context) ([]Order, error)
	GetAllProducts(ctx context.Context) ([]Product, error)
	GetAvailableProducts(ctx context.Context) ([]Product, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetTopProductsByQuantity(ctx context.Context, limit int32) ([]Product, error)
	IncreaseProductQuantity(ctx context.Context, arg IncreaseProductQuantityParams) error
	ProductExists(ctx context.Context, id int64) (bool, error)
	SearchProducts(ctx context.Context, dollar_1 pgtype.Text) ([]Product, error)
	UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) error
	UpdateProductWhereID(ctx context.Context, arg UpdateProductWhereIDParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
