// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    customer_id,
    status
) VALUES ($1, $2)
RETURNING id, customer_id, status, created_at
`

type CreateOrderParams struct {
	CustomerID int64  `json:"customer_id"`
	Status     string `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.CustomerID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO orders_items (
    order_id,
     product_id, quantity , price_in_cents
) VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price_in_cents, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID      int64   `json:"order_id"`
	ProductID    int64   `json:"product_id"`
	Quantity     int32   `json:"quantity"`
	PriceInCents float64 `json:"price_in_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrdersItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceInCents,
	)
	var i OrdersItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceInCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    price_in_cents,
    quantity
)
VALUES ($1, $2, $3)
RETURNING id, name, price_in_cents, quantity, created_at, updated_at
`

type CreateProductParams struct {
	Name         string  `json:"name"`
	PriceInCents float64 `json:"price_in_cents"`
	Quantity     int32   `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceInCents, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT id, customer_id, status, created_at
FROM orders
ORDER BY created_at DESC
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, name, price_in_cents, quantity, created_at, updated_at
FROM products
ORDER BY created_at DESC
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableProducts = `-- name: GetAvailableProducts :many
SELECT id, name, price_in_cents, quantity, created_at, updated_at
FROM products
WHERE quantity > 0
ORDER BY created_at DESC
`

func (q *Queries) GetAvailableProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAvailableProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, status, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price_in_cents, quantity, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopProductsByQuantity = `-- name: GetTopProductsByQuantity :many
SELECT id, name, price_in_cents, quantity, created_at, updated_at
FROM products
ORDER BY quantity DESC
LIMIT $1
`

func (q *Queries) GetTopProductsByQuantity(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, getTopProductsByQuantity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseProductQuantity = `-- name: IncreaseProductQuantity :exec
UPDATE products
SET 
    quantity = quantity + $1,
    updated_at = now()
WHERE id = $2
`

type IncreaseProductQuantityParams struct {
	Quantity int32 `json:"quantity"`
	ID       int64 `json:"id"`
}

func (q *Queries) IncreaseProductQuantity(ctx context.Context, arg IncreaseProductQuantityParams) error {
	_, err := q.db.Exec(ctx, increaseProductQuantity, arg.Quantity, arg.ID)
	return err
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS (
    SELECT 1 FROM products WHERE id = $1
)
`

func (q *Queries) ProductExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, productExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, name, price_in_cents, quantity, created_at, updated_at
FROM products
WHERE name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) SearchProducts(ctx context.Context, dollar_1 pgtype.Text) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductPrice = `-- name: UpdateProductPrice :exec
UPDATE products
SET 
    price_in_cents = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateProductPriceParams struct {
	PriceInCents float64 `json:"price_in_cents"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) error {
	_, err := q.db.Exec(ctx, updateProductPrice, arg.PriceInCents, arg.ID)
	return err
}

const updateProductWhereID = `-- name: UpdateProductWhereID :one
UPDATE products
SET 
    name = $1,
    price_in_cents = $2,
    quantity = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, name, price_in_cents, quantity, created_at, updated_at
`

type UpdateProductWhereIDParams struct {
	Name         string  `json:"name"`
	PriceInCents float64 `json:"price_in_cents"`
	Quantity     int32   `json:"quantity"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateProductWhereID(ctx context.Context, arg UpdateProductWhereIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductWhereID,
		arg.Name,
		arg.PriceInCents,
		arg.Quantity,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
